# Altera para LocalExecutor (consome muito menos memória que o CeleryExecutor padrão)
executor: "LocalExecutor"

# Desativa recursos que você não vai usar no momento para poupar RAM
postgresql:
  enabled: true # Mantém o Postgres interno apenas para os metadados do Airflow
  image:
    repository: bitnamilegacy/postgresql # Aponta para o arquivo morto onde a tag existe
    tag: "16.1.0-debian-11-r15"

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@banvic.com
    firstName: Admin
    lastName: BanVic
    password: "$(ADMIN_PASSWORD)"

createUserJob:
  env:
    - name: ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-webserver-password
          key: password
