apiVersion: v1
kind: Service
metadata:
  name: sftp-server
  namespace: airflow
spec:
  selector:
    app: sftp-server
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      containers:
        - name: sftp
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
          env:
            - name: SFTP_USER
              valueFrom:
                secretKeyRef:
                  name: sftp-credentials
                  key: username
            - name: SFTP_PASS
              valueFrom:
                secretKeyRef:
                  name: sftp-credentials
                  key: password
          args: ["$(SFTP_USER):$(SFTP_PASS):1001:1001:upload"]
